"""create plants table

Revision ID: 527b3b3177d1
Revises: 
Create Date: 2026-07-29 21:41:32.229687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '527b3b3177d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('common_name', sa.String(), nullable=False),
    sa.Column('scientific_name', sa.String(), nullable=True),
    sa.Column('life_cycle', sa.String(), nullable=True),
    sa.Column('light_needs', sa.String(), nullable=True),
    sa.Column('ph_min', sa.Float(), nullable=True),
    sa.Column('ph_max', sa.Float(), nullable=True),
    sa.Column('soil_type', sa.String(), nullable=True),
    sa.Column('watering_frequency', sa.String(), nullable=True),
    sa.Column('spacing', sa.String(), nullable=True),
    sa.Column('planting_season', sa.String(), nullable=True),
    sa.Column('days_to_harvest', sa.Integer(), nullable=True),
    sa.Column('common_pests', sa.String(), nullable=True),
    sa.Column('common_diseases', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plants')
    # ### end Alembic commands ###
