# app/agents/flowers.py
#
# Categories in this list (206 total):
# - Annuals (30)
# - Perennials (55)
# - Roses (6)
# - Bulbs / corms / rhizomes (30)
# - Flowering shrubs (24)
# - Vines / climbers (9)
# - Wildflowers / native (23)
# - Herbs grown for flowers / ornamental (8)
# - Tropical / houseplant-adjacent flowering (10)
# - Ground covers / low-growing flowering (9)
# - Ornamental grasses with notable blooms (2)
#
# Other stats worth knowing:
# - Largest category: Perennials (55, ~27% of the list)
# - Smallest category: Ornamental grasses (2)
# - Verified: no duplicate names, no slug collisions (lowercased/hyphenated)
# - Entries sorted alphabetically within each category (case-insensitive)

flowers = [
    # Annuals (30)
    "Ageratum",
    "Alyssum",
    "Bachelor's Button",
    "Begonia",
    "Calendula",
    "Celosia",
    "Cockscomb",
    "Cosmos",
    "Four O'Clock",
    "Gazania",
    "Impatiens",
    "Larkspur",
    "Lobelia",
    "Marigold",
    "Moonflower",
    "Morning Glory",
    "Nasturtium",
    "Pansy",
    "Petunia",
    "Portulaca",
    "Salvia",
    "Snapdragon",
    "Strawflower",
    "Sunflower",
    "Sweet Alyssum",
    "Sweet Pea",
    "Verbena",
    "Vinca",
    "Zinnia",
    "Zonal Geranium",
    # Perennials (55)
    "Anemone",
    "Aster",
    "Astilbe",
    "Baby's Breath",
    "Balloon Flower",
    "Bee Balm",
    "Black-Eyed Susan",
    "Blanket Flower",
    "Bleeding Heart",
    "Brunnera",
    "Cardinal Flower",
    "Carnation",
    "Catmint",
    "Chrysanthemum",
    "Columbine",
    "Coneflower",
    "Coral Bells",
    "Coreopsis",
    "Daylily",
    "Delphinium",
    "English Daisy",
    "Epimedium",
    "Evening Primrose",
    "False Indigo",
    "Foxglove",
    "Gaillardia",
    "Gaura",
    "Gerbera Daisy",
    "Globe Thistle",
    "Hibiscus",
    "Hollyhock",
    "Hosta",
    "Iris",
    "Joe Pye Weed",
    "Lamb's Ear",
    "Lavender",
    "Ligularia",
    "Lungwort",
    "Lupine",
    "Penstemon",
    "Peony",
    "Phlox",
    "Primrose",
    "Rodgersia",
    "Rudbeckia",
    "Russian Sage",
    "Salvia Perennial",
    "Sedum",
    "Shasta Daisy",
    "Statice",
    "Sweet William",
    "Threadleaf Coreopsis",
    "Turtlehead",
    "Veronica",
    "Yarrow",
    # Roses (6)
    "Climbing Rose",
    "Floribunda Rose",
    "Hybrid Tea Rose",
    "Rose",
    "Rugosa Rose",
    "Shrub Rose",
    # Bulbs / corms / rhizomes (30)
    "Allium",
    "Amaryllis",
    "Anemone Bulb",
    "Asiatic Lily",
    "Autumn Crocus",
    "Begonia Tuberous",
    "Caladium",
    "Calla Lily",
    "Canna Lily",
    "Chionodoxa",
    "Crocosmia",
    "Crocus",
    "Cyclamen",
    "Daffodil",
    "Dahlia",
    "Freesia",
    "Fritillaria",
    "Gladiolus",
    "Grape Hyacinth",
    "Hyacinth",
    "Iris Bulb",
    "Lily",
    "Oriental Lily",
    "Ranunculus",
    "Scilla",
    "Snowdrop",
    "Star of Bethlehem",
    "Tulip",
    "Windflower",
    "Winter Aconite",
    # Flowering shrubs (24)
    "Azalea",
    "Beautybush",
    "Bougainvillea",
    "Butterfly Bush",
    "Camellia",
    "Chaenomeles",
    "Daphne",
    "Deutzia",
    "Flowering Quince",
    "Forsythia",
    "Gardenia",
    "Hydrangea",
    "Kerria",
    "Lilac",
    "Mock Orange",
    "Oleander",
    "Peony Tree",
    "Potentilla",
    "Rhododendron",
    "Rose of Sharon",
    "Spirea",
    "Viburnum",
    "Weigela",
    "Witch Hazel",
    # Vines / climbers (9)
    "Black-Eyed Susan Vine",
    "Clematis",
    "Climbing Hydrangea",
    "Honeysuckle",
    "Jasmine",
    "Mandevilla",
    "Passionflower",
    "Trumpet Vine",
    "Wisteria",
    # Wildflowers / native (23)
    "Black-Eyed Coneflower",
    "Blazing Star",
    "Bloodroot",
    "Blue Flag Iris",
    "Butterfly Weed",
    "Cardinal Flower Wild",
    "Culver's Root",
    "Goldenrod",
    "Indian Paintbrush",
    "Ironweed",
    "Jack-in-the-Pulpit",
    "Milkweed",
    "New England Aster",
    "Ox-Eye Daisy",
    "Prairie Smoke",
    "Purple Coneflower",
    "Queen Anne's Lace",
    "Spiderwort",
    "Trillium",
    "Virginia Bluebells",
    "Wild Bergamot",
    "Wild Columbine",
    "Wild Geranium",
    # Herbs grown for flowers / ornamental (8)
    "Bachelor Buttons",
    "Borage",
    "Calendula Herb",
    "Chamomile",
    "Echinacea",
    "Feverfew",
    "Lavender Herb",
    "Yarrow Herb",
    # Tropical / houseplant-adjacent flowering (10)
    "Anthurium",
    "Bird of Paradise",
    "Bromeliad",
    "Ginger Lily",
    "Heliconia",
    "Hibiscus Tropical",
    "Ixora",
    "Orchid",
    "Passion Flower Tropical",
    "Plumeria",
    # Ground covers / low-growing flowering (9)
    "Ajuga",
    "Bergenia",
    "Creeping Phlox",
    "Creeping Thyme",
    "Lily of the Valley",
    "Moss Phlox",
    "Sweet Woodruff",
    "Vinca Minor",
    "Wood Anemone",
    # Ornamental grasses with notable blooms (2)
    "Fountain Grass Purple",
    "Pampas Grass",
]
# app/agents/flowers.py
# 206 flowers, grouped by category for easy pruning.

# Categories in this list:
# - Annuals
# - Perennials
# - Roses
# - Bulbs / corms / rhizomes
# - Flowering shrubs
# - Vines / climbers
# - Wildflowers / native
# - Herbs grown for flowers / ornamental
# - Tropical / houseplant-adjacent flowering
# - Ground covers / low-growing flowering
# - Ornamental grasses with notable blooms

flowers = [
    # Annuals
    "Marigold",
    "Zinnia",
    "Petunia",
    "Pansy",
    "Cosmos",
    "Sunflower",
    "Snapdragon",
    "Sweet Pea",
    "Nasturtium",
    "Impatiens",
    "Begonia",
    "Alyssum",
    "Calendula",
    "Cockscomb",
    "Larkspur",
    "Bachelor's Button",
    "Four O'Clock",
    "Morning Glory",
    "Moonflower",
    "Salvia",
    "Verbena",
    "Ageratum",
    "Celosia",
    "Gazania",
    "Lobelia",
    "Portulaca",
    "Strawflower",
    "Sweet Alyssum",
    "Vinca",
    "Zonal Geranium",
    # Perennials
    "Peony",
    "Iris",
    "Daylily",
    "Hosta",
    "Coneflower",
    "Black-Eyed Susan",
    "Shasta Daisy",
    "Coreopsis",
    "Yarrow",
    "Bee Balm",
    "Aster",
    "Chrysanthemum",
    "Phlox",
    "Columbine",
    "Delphinium",
    "Foxglove",
    "Hollyhock",
    "Hibiscus",
    "Lupine",
    "Gaillardia",
    "Rudbeckia",
    "Sedum",
    "Salvia Perennial",
    "Catmint",
    "Lavender",
    "Russian Sage",
    "Astilbe",
    "Bleeding Heart",
    "Coral Bells",
    "Lamb's Ear",
    "Veronica",
    "Gaura",
    "Penstemon",
    "Baby's Breath",
    "Statice",
    "Anemone",
    "Gerbera Daisy",
    "English Daisy",
    "Carnation",
    "Sweet William",
    "Balloon Flower",
    "Globe Thistle",
    "Cardinal Flower",
    "Joe Pye Weed",
    "Turtlehead",
    "Lungwort",
    "Primrose",
    "Evening Primrose",
    "Blanket Flower",
    "Threadleaf Coreopsis",
    "False Indigo",
    "Ligularia",
    "Rodgersia",
    "Brunnera",
    "Epimedium",
    # Roses
    "Rose",
    "Climbing Rose",
    "Shrub Rose",
    "Hybrid Tea Rose",
    "Floribunda Rose",
    "Rugosa Rose",
    # Bulbs / corms / rhizomes
    "Tulip",
    "Daffodil",
    "Crocus",
    "Hyacinth",
    "Gladiolus",
    "Dahlia",
    "Ranunculus",
    "Anemone Bulb",
    "Lily",
    "Asiatic Lily",
    "Oriental Lily",
    "Calla Lily",
    "Amaryllis",
    "Freesia",
    "Allium",
    "Snowdrop",
    "Grape Hyacinth",
    "Iris Bulb",
    "Canna Lily",
    "Begonia Tuberous",
    "Caladium",
    "Crocosmia",
    "Scilla",
    "Fritillaria",
    "Windflower",
    "Winter Aconite",
    "Cyclamen",
    "Autumn Crocus",
    "Star of Bethlehem",
    "Chionodoxa",
    # Flowering shrubs
    "Hydrangea",
    "Azalea",
    "Rhododendron",
    "Camellia",
    "Lilac",
    "Forsythia",
    "Peony Tree",
    "Weigela",
    "Spirea",
    "Viburnum",
    "Butterfly Bush",
    "Rose of Sharon",
    "Mock Orange",
    "Beautybush",
    "Deutzia",
    "Flowering Quince",
    "Witch Hazel",
    "Daphne",
    "Gardenia",
    "Bougainvillea",
    "Oleander",
    "Potentilla",
    "Kerria",
    "Chaenomeles",
    # Vines / climbers
    "Clematis",
    "Wisteria",
    "Honeysuckle",
    "Trumpet Vine",
    "Passionflower",
    "Mandevilla",
    "Jasmine",
    "Black-Eyed Susan Vine",
    "Climbing Hydrangea",
    # Wildflowers / native
    "Purple Coneflower",
    "Butterfly Weed",
    "Milkweed",
    "Wild Bergamot",
    "Indian Paintbrush",
    "Black-Eyed Coneflower",
    "Ox-Eye Daisy",
    "Queen Anne's Lace",
    "Goldenrod",
    "New England Aster",
    "Wild Columbine",
    "Blue Flag Iris",
    "Cardinal Flower Wild",
    "Prairie Smoke",
    "Blazing Star",
    "Wild Geranium",
    "Trillium",
    "Bloodroot",
    "Jack-in-the-Pulpit",
    "Virginia Bluebells",
    "Spiderwort",
    "Ironweed",
    "Culver's Root",
    # Herbs grown for flowers / ornamental
    "Chamomile",
    "Borage",
    "Bachelor Buttons",
    "Calendula Herb",
    "Yarrow Herb",
    "Echinacea",
    "Feverfew",
    "Lavender Herb",
    # Tropical / houseplant-adjacent flowering
    "Orchid",
    "Bird of Paradise",
    "Plumeria",
    "Hibiscus Tropical",
    "Anthurium",
    "Bromeliad",
    "Passion Flower Tropical",
    "Ixora",
    "Ginger Lily",
    "Heliconia",
    # Ground covers / low-growing flowering
    "Creeping Phlox",
    "Moss Phlox",
    "Sweet Woodruff",
    "Ajuga",
    "Creeping Thyme",
    "Vinca Minor",
    "Lily of the Valley",
    "Wood Anemone",
    "Bergenia",
    # Ornamental grasses with notable blooms
    "Pampas Grass",
    "Fountain Grass Purple",
]
